### ISSUE TITLE
Tela de Dashboard

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/presente-app#12]
- [x] Implementar lista das disciplinas agendadas para o dia atual.
- [ ] Integrar lista com backend para obter dados das disciplinas do dia.
- [x] Implementar botão "Presente" para marcar presença.
- [x] Implementar botão "Ausente" para marcar ausência.
- [x] Integrar botões com backend para registrar presença/ausência.
- [ ] Implementar botão para acessar a tela de histórico de faltas.
- [x] Implementar barra de navegação fixa no rodapé com botões para navegar para o Dashboard, Cadastro de Disciplina, Histórico, e Perfil.

**Comment by erika-hortencia** [comment]
## Itens faltantes:
- [ ] Integrar com o backend (falta e presença está sendo atualizada no contador)
- [ ] Implementar aceso à atividade (tela de detalhes da atividade ainda não foi criada)
