### ISSUE TITLE
Tela de Histórico de Faltas

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/presente-app#13]
- [x] Implementar filtro por disciplina.
   - [x] Implementar filtro por período de tempo.
   - [x] Implementar exibição da lista de faltas registradas (data, disciplina e status).
   - [ ] Integrar lista com backend para obter dados de faltas.
   - [x] Implementar barra de navegação fixa no rodapé com botões para navegar para o Dashboard, Cadastro de Disciplina, Histórico, e Perfil.

**Comment by erika-hortencia** [comment]
- [x] Implementado o filtro por disciplina
- [x] Implementado o filtro por período de tempo
- [x] Barra de navegação ok por default

 ## Nova dependência
Para os filtros foi utilizada o componente **picker** do react, para instalar:
`npm install @react-native-picker/picker`

##Para implementar
- [ ] O seletor de atividade deve receber as atividades cadastradas no backend
- [ ] const logs, que armazena a data de início, data de fim e atividade selecionada deve ser enviado para o backend
- [ ] handleDetailsPress deve ser ajustado para encaminhar para a página da atividade selecionada
