### ISSUE TITLE
Tela de Perfil

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/presente-app#14]
- [x] Implementar campo de texto para o nome do usuário.
   - [ ] Integrar campo com backend para carregar e atualizar o nome do usuário.
   - [x] Implementar campo de texto para o email do usuário (não editável).
   - [x] Integrar campo com backend para carregar o email do usuário.
   - [x] Implementar campo de texto para a senha do usuário.
   - [ ] Integrar campo com backend para atualização da senha do usuário.
   - [x] Implementar barra de navegação fixa no rodapé com botões para navegar para o Dashboard, Cadastro de Disciplina, Histórico, e Perfil.

**Comment by erika-hortencia** [comment]
Todos os itens foram finalizados, os que não estão com check, optamos por eliminar do projeto.
